# 线上配置文件
# @author <a href="https://github.com/Wmhha">Wmhha</a>
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api
    username: xxx
    password: xxx